### ISSUE TITLE
bug: errors that have recently been manifesting locally and in a live env

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1414]
```
kargo-management-controller-5669885dcd-7kzqp management-controller time="2024-01-23T20:05:10Z" level=info msg="Starting Kargo Management Controller" commit=8b6f58a4ddfc81e004bb782de69a45a575d29a44 version=main
kargo-management-controller-5669885dcd-7kzqp management-controller [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
kargo-management-controller-5669885dcd-7kzqp management-controller Detected at:
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  goroutine 87 [running]:
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  runtime/debug.Stack()
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/log/log.go:60 +0xcd
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Error(0xc00047a080, {0x20b7540, 0xc00056e040}, {0x1e05c45, 0x21}, {0x0, 0x0, 0x0})
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/log/deleg.go:139 +0x5d
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  github.com/go-logr/logr.Logger.Error({{0x20d9d20?, 0xc00047a080?}, 0x0?}, {0x20b7540, 0xc00056e040}, {0x1e05c45, 0x21}, {0x0, 0x0, 0x0})
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:301 +0xda
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1({0x20d49b8?, 0xc00065ec80?})
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/source/kind.go:68 +0x1a9
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1(0xc000654ee0?, {0x20d49b8?, 0xc00065ec80?})
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/loop.go:53 +0x52
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x20d49b8, 0xc00065ec80}, {0x20d30d0?, 0xc000654ee0}, 0x1, 0x0, 0x0?)
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/loop.go:54 +0x117
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel({0x20d49b8, 0xc00065ec80}, 0x0?, 0x0?, 0x0?)
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/poll.go:33 +0x56
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1()
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/source/kind.go:56 +0xee
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  created by sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start in goroutine 82
kargo-management-controller-5669885dcd-7kzqp management-controller 	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/source/kind.go:48 +0x1d8
```

This may also have been related:

```
failed to wait for project caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.Project
```

I am a bit suspicious of recent controller-runtime  upgrades.

**Comment by krancour** [comment]
I think it's this:

https://github.com/kubernetes-sigs/controller-runtime/issues/2622

**Comment by jessesuen** [comment]
I don't think so. This is about `timed out waiting for cache to be synced for Kind *v1alpha1.Project`. 

I think the `log.SetLogger(...) was never called; logs will not be displayed.` error is benign, and just indicates we need to set a logger for controller runtime.

**Comment by jessesuen** [comment]
> I think the log.SetLogger(...) was never called; logs will not be displayed. error is benign, and just indicates we need to set a logger for controller runtime.

[This commit](https://github.com/akuity/kargo/pull/1418/commits/a4e5d8d7098067b661f145a170ab5b6d319b3410) should silence the `log.SetLogger(...) was never called; logs will not be displayed` error.

**Comment by jessesuen** [comment]
This was a network policy issue in my environment. Closing.
